project:
  type: website

website:
  title: "Titanic: End-to-End Classification Case Study"
  description: "A complete machine learning workflow using the Kaggle Titanic dataset."
  site-url: "https://ianlopezdiaz.github.io/kaggle-titanic"
  #favicon: images/favicon.ico # optional - remove if there is none
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notebooks"
        menu:
          - href: notebooks/01_exploratory_data_analysis.ipynb
            text: "01 - Exploratory Data Analysis (EDA)"
          - href: notebooks/02_feature_engineering.ipynb
            text: "02 - Feature engineering"
          - href: notebooks/03_modeling_and_evaluation.ipynb
            text: "03 - Modeling and Evaluation"
    right:
      - text: "🇧🇷 Português"
        href: "https://ianlopezdiaz.github.io/kaggle-titanic-pt"
      - text: Portfolio
        href: https://ianlopezdiaz.github.io/portfolio
      - icon: github
        href: https://github.com/ianlopezdiaz/kaggle-titanic


  page-footer:
    left: "© 2026 ianlopezdiaz"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      dark: solar
      light: minty
    toc: true
    toc-depth: 3
    code-fold: show
    highlight-style: github
